# serverless.yml
service:
    name: proxy

provider:
  name: cloudflare
  environment:
  config:
    accountId: ${env:CLOUDFLARE_ACCOUNT_ID}
    zoneId: ${env:CLOUDFLARE_ZONE_ID}    

plugins:
  - serverless-dotenv-plugin
  - serverless-scriptable-plugin
  - serverless-cloudflare-workers

custom:
  scriptHooks:
    package:createDeploymentArtifacts: npm run build
  dotenv:
    path: ./.env

functions:
  cloudworker-router-examples:
    # What the script will be called on Cloudflare (this property value must match the function name one line above)
    name: cloudworker-router-examples
    # The name of the script on your machine, omitting the .js file extension
    script: 'dist/bundle'
    webpack: false
    events:
      - http:
          url: 'router.ahlstrand.es/*'
          method: ANY